### ISSUE TITLE
suggested edit to stack.yaml

### ISSUE THREAD

**Issue by esjmb** [Farhan1989/CS7051.G3#2]
I understand you have a compiler error and I suspect it might be a ghc 8.0.1 issue?

anyway, by adding the following to the CS7051.G3/G3UI/stack.yaml file i was able to compile the project.

```
compiler: ghc-7.10.3
docker:
  enable: true
```

You probably don't have to build on docker - I do at the moment because i'm running a beta of os x sierra and there are some compatibility issues with ghc. But if you do find a continuing build problem then try building on docker, as this provides a standard build environment.

**Comment by Farhan1989** [comment]
Thanks Professor.. It worked for me..
